@includeIf('theme.main::partials.sliders')
@includeIf('theme.main::partials.about-us')
@includeIf('theme.main::partials.our-services')
@includeIf('theme.main::partials.our-shop')
@includeIf('theme.main::partials.testimonials')
@includeIf('theme.main::partials.blogs-and-follow')